<script setup>
import { useAuthStore } from "@/stores/useAuthStore";

const authStore = useAuthStore();
</script>

<template>
  <section class="w-full flex flex-col">
    <div class="p-4 max-w-screen-xl mx-auto">
      <!-- Main Title -->
      <h1 class="text-stone-900 my-4 md:my-8 text-3xl md:text-4xl lg:text-5xl font-semibold text-center">
        Restore balance with <span class="text-emerald-700 font-extrabold">EcoTrail</span>
      </h1>

      <!-- Subtitle Text -->
      <h2 class="text-stone-800 text-lg md:text-2xl my-4 max-w-3xl mx-auto text-center">
        Your all-in-one platform to measure, reduce, and offset your company's carbon footprint.
        <span class="underline decoration-4 decoration-emerald-500 font-semibold">Ready to make a difference?</span>
      </h2>

      <!-- Main Section -->
      <div class="px-10 md:px-20 md:py-5 py-10 my-6">
        <p class="text-stone-900 text-base md:text-lg my-2">
          Optimize up to <span class="font-semibold text-emerald-700">80%</span> of the time spent calculating and
          managing your environmental impact with our powerful tools.
        </p>

        <p class="text-stone-900 text-base md:text-lg">
          As businesses strive to become more sustainable, understanding and reducing their carbon footprint has never
          been more crucial. With EcoTrail, you can seamlessly measure, reduce, and offset the emissions generated by
          your operations. Empower your company to make data-driven decisions and contribute to a cleaner, greener
          future.
        </p>

        <blockquote class="p-4 my-4 border-s-4 border-emerald-300 bg-emerald-700/20">
          <p class="text-xl md:text-2xl italic font-medium leading-relaxed text-stone-700">
            "EcoTrail is a game-changer. It simplifies the complex task of calculating carbon footprints, allowing
            businesses to take meaningful steps towards sustainability with ease and efficiency."
          </p>
        </blockquote>

        <p class="text-stone-900 text-base md:text-lg">
          With EcoTrail, you not only gain the tools to track your carbon emissions, but you also unlock actionable
          insights to help you achieve Net Zero. From renewable energy certifications to carbon offset programs, our
          platform offers a complete solution for businesses committed to making a real impact on climate change.
        </p>
      </div>

      <!-- Highlight Section -->
      <div class="highlight-section p-8 my-8 rounded-lg">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div class="border-accent border-l-4 pl-4">
            <span class="primary-text">5,000+</span>
            <p class="secondary-text">Tons of CO2 offset</p>
          </div>
          <div class="border-accent border-l-4 pl-4">
            <span class="primary-text">1,200+</span>
            <p class="secondary-text">Active users</p>
          </div>
          <!-- Guest User Call-to-Action -->
          <div v-if="!authStore.isLoggedIn" class="accent-color p-4 rounded-lg text-center">
            <span class="text-xl font-bold">Join the action!</span>
          </div>
          <!-- Authenticated User Call-to-Action -->
          <div v-else class="accent-color p-4 rounded-lg text-center">
            <span class="text-xl font-bold">Continue helping!</span>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
