<script setup>
import SectionSubtitle from "@/components/typography/SectionSubtitle.vue";
import Hero from "@/components/home/Hero.vue";
import ContentSection from "@/components/typography/ContentSection.vue";
import Features from "@/components/home/Features.vue";
import HowItWorks from "@/components/home/HowItWorks.vue";
import CallToAction from "@/components/home/CallToAction.vue";
import Testimonials from "@/components/home/Testimonials.vue";

const homeContent = [
  "Optimize up to <span class='font-semibold text-emerald-700'>80%</span> of the time spent calculating and managing your environmental impact with our powerful tools.",
  "As businesses strive to become more sustainable, understanding and reducing their carbon footprint has never been more crucial. With EcoTrail, you can seamlessly measure, reduce, and offset the emissions generated by your operations. Empower your company to make data-driven decisions and contribute to a cleaner, greener future.",
  "With EcoTrail, you not only gain the tools to track your carbon emissions, but you also unlock actionable insights to help you achieve Net Zero. From renewable energy certifications to carbon offset programs, our platform offers a complete solution for businesses committed to making a real impact on climate change.",
];

const homeQuote =
  "EcoTrail is a game-changer. It simplifies the complex task of calculating carbon footprints, allowing businesses to take meaningful steps towards sustainability with ease and efficiency.";
</script>

<template>
  <section class="w-full flex flex-col">
    <div class="p-0 sm:p-4 max-w-screen-xl mx-auto">
      <div class="relative overflow-hidden bg-gradient-to-b from-stone-100 to-transparent pt-12 sm:pt-24 sm:rounded-lg">
        <Hero />
        <div class="mt-10 sm:mt-20">
          <SectionSubtitle
            text="Your all-in-one platform to measure, reduce, and offset your company's carbon footprint."
            highlight="Ready to make a difference?"
          />
        </div>
        <ContentSection :content="homeContent" :quote="homeQuote" />
      </div>
      <Features />
      <Testimonials />
      <HowItWorks />
      <CallToAction />
    </div>
  </section>
</template>
