<script setup>
import Testimonial from "@/components/home/Testimonial.vue";
</script>

<template>
  <div class="px-5 sm:px-10 md:px-20 py-5 md:py-10">
    <p class="text-stone-900 text-base md:text-lg my-2">
      Optimize up to <span class="font-semibold text-emerald-700">80%</span> of the time spent calculating and managing
      your environmental impact with our powerful tools.
    </p>
    <p class="text-stone-900 text-base md:text-lg">
      As businesses strive to become more sustainable, understanding and reducing their carbon footprint has never been
      more crucial. With EcoTrail, you can seamlessly measure, reduce, and offset the emissions generated by your
      operations. Empower your company to make data-driven decisions and contribute to a cleaner, greener future.
    </p>
    <Testimonial
      quote="EcoTrail is a game-changer. It simplifies the complex task of calculating carbon footprints, allowing businesses to take meaningful steps towards sustainability with ease and efficiency."
    />
    <p class="text-stone-900 text-base md:text-lg">
      With EcoTrail, you not only gain the tools to track your carbon emissions, but you also unlock actionable insights
      to help you achieve Net Zero. From renewable energy certifications to carbon offset programs, our platform offers
      a complete solution for businesses committed to making a real impact on climate change.
    </p>
  </div>
</template>
